// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoef;

#nullable disable

namespace proyectoAspCore.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20220630004452_DataSeed_fix")]
    partial class DataSeed_fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("proyectoef.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("70c5d507-97c8-4a27-ba63-6f6b64de0371"),
                            Nombre = "Pendientes",
                            Peso = 40
                        },
                        new
                        {
                            CategoriaId = new Guid("bbe85b12-cd36-4e4f-91fe-12c9dc9d9e8d"),
                            Nombre = "En Progreso",
                            Peso = 60
                        },
                        new
                        {
                            CategoriaId = new Guid("e02f60b9-bc30-47e2-b4a2-7f85745b42c6"),
                            Nombre = "No Iniciada",
                            Peso = 10
                        });
                });

            modelBuilder.Entity("proyectoef.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("90559269-84fb-4c26-a93b-311787b0f522"),
                            CategoriaId = new Guid("70c5d507-97c8-4a27-ba63-6f6b64de0371"),
                            FechaCreacion = new DateTime(2022, 6, 29, 19, 44, 52, 307, DateTimeKind.Local).AddTicks(5459),
                            PrioridadTarea = 1,
                            Titulo = "Tender cama"
                        },
                        new
                        {
                            TareaId = new Guid("9892d8af-9648-4fe9-8433-7fd2a2b36055"),
                            CategoriaId = new Guid("bbe85b12-cd36-4e4f-91fe-12c9dc9d9e8d"),
                            FechaCreacion = new DateTime(2022, 6, 29, 19, 44, 52, 307, DateTimeKind.Local).AddTicks(5498),
                            PrioridadTarea = 2,
                            Titulo = "Clases Programación"
                        },
                        new
                        {
                            TareaId = new Guid("3c2428ff-5631-417e-8b10-8f2a309acefd"),
                            CategoriaId = new Guid("e02f60b9-bc30-47e2-b4a2-7f85745b42c6"),
                            FechaCreacion = new DateTime(2022, 6, 29, 19, 44, 52, 307, DateTimeKind.Local).AddTicks(5501),
                            PrioridadTarea = 0,
                            Titulo = "Cocinar"
                        });
                });

            modelBuilder.Entity("proyectoef.Models.Tarea", b =>
                {
                    b.HasOne("proyectoef.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyectoef.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
